version: "3"

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./chat_app:/chat_app
    environment:
      - DB_HOST=database
    depends_on:
      - database
    env_file:
      - .env

    command: python3 manage.py runserver 0.0.0.0:8000

  database:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
